### ISSUE TITLE
Error 500 - java.util.IllegalFormatConversionException: d != java.lang.Double

### ISSUE THREAD

**Issue by mrmookie** [twitter/GraphJet#67]
When running the demo with examples I'm getting the following:

curl http://localhost:8888/tweetHashtagGraph/topTweets?k=5
<html>
<head>
<meta http-equiv="Content-Type" content="text/html;charset=ISO-8859-1"/>
<title>Error 500 </title>
</head>
<body>
<h2>HTTP ERROR: 500</h2>
<p>Problem accessing /tweetHashtagGraph/topTweets. Reason:
<pre>    java.util.IllegalFormatConversionException: d != java.lang.Double</pre></p>
<hr /><a href="http://eclipse.org/jetty">Powered by Jetty:// 9.3.11.v20160721</a><hr/>
</body>
</html>

Any help would be appreciated.

**Comment by praveenbom** [comment]
This issue ought to be addressed by #68 - thanks for pointing it out @mrmookie
