### ISSUE TITLE
mater build break

### ISSUE THREAD

**Issue by guimingTang** [twitter/GraphJet#93]
There seems to be a master build failure:
https://travis-ci.org/twitter/GraphJet/builds/257880397

The most recent branch that caused the build break seems to be this one:
 https://github.com/twitter/GraphJet/pull/89

Build Log:
=== Round 999
Total memory available to JVM (bytes): 959447040
Free memory (bytes): 791487960
Tests run: 7, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 110.096 sec <<< FAILURE! - in com.twitter.graphjet.bipartite.MultiSegmentPowerLawBipartiteGraphTest
testRandomConcurrentReadWrites(com.twitter.graphjet.bipartite.MultiSegmentPowerLawBipartiteGraphTest)  Time elapsed: 10.072 sec  <<< ERROR!
java.util.concurrent.CancellationException
	at com.twitter.graphjet.bipartite.MultiSegmentPowerLawBipartiteGraphTest.testRandomConcurrentReadWrites(MultiSegmentPowerLawBipartiteGraphTest.java:398)

**Comment by jerryjiangabc** [comment]
I am trying to reproduce this locally by running this particular test in the test case 500 times, and all of them passed. Let me know if you can reproduce this locally, even once.

**Comment by jerryjiangabc** [comment]
I triggered a run in master, and it passed this time. I was not sure what happened in yesterday's run. Again, it was not reproducible locally even with 500 runs. I will look into this more if it happens for the second time.
